# Generated by Django 3.2.5 on 2021-08-23 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxon', '0003_auto_20210813_2237'),
        ('genes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='genedocument',
            name='species',
            field=models.ForeignKey(default=1148, on_delete=django.db.models.deletion.PROTECT, to='taxon.taxon'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gene',
            name='data_source_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='gene',
            name='data_source_object_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='gene',
            name='gene_id',
            field=models.CharField(help_text='Example - AT1G78600', max_length=255),
        ),
        migrations.AlterField(
            model_name='gene',
            name='gene_type',
            field=models.CharField(blank=True, help_text='Example - protein_coding', max_length=255),
        ),
        migrations.AlterField(
            model_name='gene',
            name='location',
            field=models.CharField(blank=True, help_text='Example - Chromosome 1: 29566863 - 29568931', max_length=255),
        ),
        migrations.AlterField(
            model_name='gene',
            name='name',
            field=models.CharField(help_text='Example - B-box domain protein 22', max_length=255),
        ),
        migrations.AlterField(
            model_name='gene',
            name='symbol',
            field=models.CharField(help_text='Example - BBX22', max_length=255),
        ),
        migrations.AlterField(
            model_name='gene',
            name='synonyms',
            field=models.TextField(blank=True, help_text='Example - DBB3|Double B-Box 3|LZF1', max_length=2000),
        ),
    ]
