# Generated by Django 3.2.5 on 2021-08-23 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxon', '0003_auto_20210813_2237'),
        ('genes', '0002_auto_20210823_2135'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genedocument',
            options={'ordering': ['species__name']},
        ),
        migrations.AlterField(
            model_name='genedocument',
            name='species',
            field=models.ForeignKey(limit_choices_to=models.Q(('rank', 'species'), ('rank', 'subspecies'), _connector='OR'), on_delete=django.db.models.deletion.PROTECT, to='taxon.taxon'),
        ),
    ]
