# Generated by Django 3.2.5 on 2021-09-08 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genes', '0004_auto_20210825_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='gene',
            name='pubmed_id',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
