# Generated by Django 3.2.7 on 2021-09-14 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxon', '0003_auto_20210813_2237'),
        ('genes', '0005_gene_pubmed_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gene',
            name='pubmed_id',
            field=models.CharField(blank=True, help_text='comma separated if multiple, Example - 12519987,18287693', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='gene',
            name='species',
            field=models.ForeignKey(limit_choices_to=models.Q(('rank', 'species'), ('rank', 'subspecies'), _connector='OR'), on_delete=django.db.models.deletion.PROTECT, to='taxon.taxon'),
        ),
    ]
