# Generated by Django 3.2.7 on 2021-09-15 17:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('genes', '0007_auto_20210914_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='geneapproval',
            name='action',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Approve'), (2, 'Reject'), (3, 'More info requested')], default=1),
        ),
        migrations.AddField(
            model_name='geneapproval',
            name='approver',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.PROTECT, related_name='gene_approver', to='accounts.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='geneapproval',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Pending'), (2, 'Approved'), (3, 'Rejected')], default=2),
        ),
    ]
