# Generated by Django 3.2.7 on 2021-09-15 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('genes', '0010_remove_geneapproval_approver'),
    ]

    operations = [
        migrations.AddField(
            model_name='geneapproval',
            name='source_gene',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='genes.gene'),
            preserve_default=False,
        ),
    ]
