# Generated by Django 3.2.7 on 2021-10-05 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genes', '0011_geneapproval_source_gene'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geneapproval',
            name='action',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Approve'), (2, 'Reject'), (3, 'More info requested'), (4, 'Initial request, awaiting moderator')], default=4),
        ),
        migrations.AlterField(
            model_name='geneapproval',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Pending'), (2, 'Approved'), (3, 'Rejected')], default=1),
        ),
    ]
