# Generated by Django 3.2.7 on 2022-01-10 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genes', '0012_auto_20211005_1133'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissingGenesFromAliasesImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('missingGeneList', models.TextField(null=True)),
                ('aliasCount', models.IntegerField()),
            ],
        ),
    ]
