# Generated by Django 4.2.8 on 2023-12-20 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genes', '0013_missinggenesfromaliasesimport'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalgene',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical gene', 'verbose_name_plural': 'historical genes'},
        ),
        migrations.AlterField(
            model_name='historicalgene',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
