# Generated by Django 3.2.5 on 2021-09-07 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DBXref',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dbname', models.CharField(max_length=255)),
                ('fullname', models.TextField(max_length=1000)),
                ('genericURL', models.URLField(max_length=255)),
                ('exampleID', models.CharField(max_length=100)),
                ('xrefURL', models.URLField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DBXrefDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='dbxrefs/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
