# Generated by Django 3.2.5 on 2021-09-08 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbxrefs', '0002_dbxref_synonyms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbxref',
            name='xrefURL',
            field=models.URLField(blank=True, max_length=255),
        ),
    ]
