# Generated by Django 3.2.5 on 2021-09-08 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbxrefs', '0003_alter_dbxref_xrefurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbxref',
            name='exampleID',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
