# Generated by Django 3.2.5 on 2021-09-08 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbxrefs', '0004_alter_dbxref_exampleid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbxref',
            name='exampleID',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dbxref',
            name='synonyms',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dbxref',
            name='xrefURL',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
