# Generated by Django 3.2.7 on 2021-10-06 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbxrefs', '0005_auto_20210908_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbxref',
            name='dbname',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
