# Generated by Django 3.2.7 on 2021-12-14 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbxrefs', '0007_auto_20211214_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbxref',
            name='exampleID',
            field=models.CharField(blank=True, help_text='Example - At2g17950', max_length=100, null=True),
        ),
    ]
