# Generated by Django 3.2.5 on 2021-07-27 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210726_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='needs_approval',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Requestor', 'Requestor'), ('Contributor', 'Contributor'), ('Curator', 'Curator'), ('Moderator', 'Moderator'), ('Superuser', 'Superuser')], default='Requestor', max_length=12),
        ),
    ]
