# Generated by Django 3.2.5 on 2021-08-25 21:35

import accounts.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_user_contact_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='orcid',
            field=models.URLField(default='https://orcid.org/0000-0002-1825-0097', help_text='Example: 0000-0001-2345-6789', max_length=40, validators=[django.core.validators.URLValidator, accounts.models.orcIDValidator]),
            preserve_default=False,
        ),
    ]
