# Generated by Django 3.2.7 on 2022-08-15 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_orcid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='needs_approval',
            new_name='is_approved',
        ),
    ]
