# Generated by Django 3.2.7 on 2021-10-20 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='evidence_code',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Inferred from Expression Pattern (IEP)'), (2, 'Inferred from Direct Assay (IDA)'), (3, 'Inferred from Mutant Phenotype (IMP)'), (4, 'Inferred from Genetic Interaction (IGI)'), (5, 'Inferred from Physical Interaction (IPI)'), (6, 'Inferred by Association of Genotype from Phenotype (IAGP)'), (7, 'Inferred by Curator (IC)'), (8, 'Inferred from Electronic Annotation (IEA)'), (9, 'Inferred from Sequence or structural Similarity (ISS)'), (10, 'Non-traceable Author Statement (NAS)'), (11, 'Traceable Author Statement (TAS)'), (12, 'No biological Data available (ND)'), (13, 'Inferred from Sequence Model (ISM)'), (14, 'Inferred from Reviewed Computational Analysis (RCA)'), (15, 'Inferred from Experiment (EXP)'), (16, 'Inferred from High Throughput Experiment (HTP)'), (17, 'Inferred from High Throughput Direct Assay (HDA)'), (18, 'Inferred from High Throughput Mutant Phenotype (HMP)'), (19, 'Inferred from High Throughput Genetic Interaction (HGI)'), (20, 'Inferred from High Throughput Expression Pattern (HEP)'), (21, 'Inferred from Biological aspect of Ancestor (IBA)'), (22, 'Inferred from Biological aspect of Descendant (IBD)'), (23, 'Inferred from Key Residues (IKR)'), (24, 'Inferred from Rapid Divergence (IRD)'), (25, 'Inferred from Sequence Orthology (ISO)'), (26, 'Inferred from Sequence Alignment (ISA)'), (27, 'Inferred from Genomic Context (IGC)')], help_text='IMP'),
        ),
        migrations.AlterField(
            model_name='annotationapproval',
            name='evidence_code',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Inferred from Expression Pattern (IEP)'), (2, 'Inferred from Direct Assay (IDA)'), (3, 'Inferred from Mutant Phenotype (IMP)'), (4, 'Inferred from Genetic Interaction (IGI)'), (5, 'Inferred from Physical Interaction (IPI)'), (6, 'Inferred by Association of Genotype from Phenotype (IAGP)'), (7, 'Inferred by Curator (IC)'), (8, 'Inferred from Electronic Annotation (IEA)'), (9, 'Inferred from Sequence or structural Similarity (ISS)'), (10, 'Non-traceable Author Statement (NAS)'), (11, 'Traceable Author Statement (TAS)'), (12, 'No biological Data available (ND)'), (13, 'Inferred from Sequence Model (ISM)'), (14, 'Inferred from Reviewed Computational Analysis (RCA)'), (15, 'Inferred from Experiment (EXP)'), (16, 'Inferred from High Throughput Experiment (HTP)'), (17, 'Inferred from High Throughput Direct Assay (HDA)'), (18, 'Inferred from High Throughput Mutant Phenotype (HMP)'), (19, 'Inferred from High Throughput Genetic Interaction (HGI)'), (20, 'Inferred from High Throughput Expression Pattern (HEP)'), (21, 'Inferred from Biological aspect of Ancestor (IBA)'), (22, 'Inferred from Biological aspect of Descendant (IBD)'), (23, 'Inferred from Key Residues (IKR)'), (24, 'Inferred from Rapid Divergence (IRD)'), (25, 'Inferred from Sequence Orthology (ISO)'), (26, 'Inferred from Sequence Alignment (ISA)'), (27, 'Inferred from Genomic Context (IGC)')], help_text='IMP'),
        ),
        migrations.AlterField(
            model_name='historicalannotation',
            name='evidence_code',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Inferred from Expression Pattern (IEP)'), (2, 'Inferred from Direct Assay (IDA)'), (3, 'Inferred from Mutant Phenotype (IMP)'), (4, 'Inferred from Genetic Interaction (IGI)'), (5, 'Inferred from Physical Interaction (IPI)'), (6, 'Inferred by Association of Genotype from Phenotype (IAGP)'), (7, 'Inferred by Curator (IC)'), (8, 'Inferred from Electronic Annotation (IEA)'), (9, 'Inferred from Sequence or structural Similarity (ISS)'), (10, 'Non-traceable Author Statement (NAS)'), (11, 'Traceable Author Statement (TAS)'), (12, 'No biological Data available (ND)'), (13, 'Inferred from Sequence Model (ISM)'), (14, 'Inferred from Reviewed Computational Analysis (RCA)'), (15, 'Inferred from Experiment (EXP)'), (16, 'Inferred from High Throughput Experiment (HTP)'), (17, 'Inferred from High Throughput Direct Assay (HDA)'), (18, 'Inferred from High Throughput Mutant Phenotype (HMP)'), (19, 'Inferred from High Throughput Genetic Interaction (HGI)'), (20, 'Inferred from High Throughput Expression Pattern (HEP)'), (21, 'Inferred from Biological aspect of Ancestor (IBA)'), (22, 'Inferred from Biological aspect of Descendant (IBD)'), (23, 'Inferred from Key Residues (IKR)'), (24, 'Inferred from Rapid Divergence (IRD)'), (25, 'Inferred from Sequence Orthology (ISO)'), (26, 'Inferred from Sequence Alignment (ISA)'), (27, 'Inferred from Genomic Context (IGC)')], help_text='IMP'),
        ),
    ]
