# Generated by Django 3.2.7 on 2023-02-08 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0003_auto_20211028_1359'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnotationOntologyTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('onto_term', models.CharField(help_text='GO:0003993', max_length=16, verbose_name='Ontology ID')),
                ('term_definition', models.TextField(blank=True, help_text='Definition of ontology term', max_length=1000, verbose_name='Ontology Term definition')),
                ('term_synonyms', models.TextField(blank=True, help_text='Term synonyms', max_length=1000, verbose_name='Ontology Term synonym')),
                ('term_is_obsolete', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='annotation',
            name='ontology_term_link',
            field=models.ForeignKey(help_text='GO:0003993', null=True, on_delete=django.db.models.deletion.PROTECT, to='annotations.annotationontologyterm', verbose_name='Ontology ID'),
        ),
        migrations.AddField(
            model_name='annotationapproval',
            name='ontology_term_link',
            field=models.ForeignKey(help_text='GO:0003993', null=True, on_delete=django.db.models.deletion.PROTECT, to='annotations.annotationontologyterm', verbose_name='Ontology ID'),
        ),
        migrations.AddField(
            model_name='historicalannotation',
            name='ontology_term_link',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='GO:0003993', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='annotations.annotationontologyterm', verbose_name='Ontology ID'),
        ),
    ]
