# Generated by Django 3.2.7 on 2023-02-08 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0005_transfer_onto_terms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annotation',
            name='ontology_id',
        ),
        migrations.RemoveField(
            model_name='annotationapproval',
            name='ontology_id',
        ),
        migrations.RemoveField(
            model_name='historicalannotation',
            name='ontology_id',
        ),
    ]
