# Generated by Django 3.2.7 on 2023-02-08 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0007_auto_20230207_1755'),
    ]

    operations = [
        migrations.RenameField(
            model_name='annotation',
            old_name='ontology_term_link',
            new_name='ontology_term',
        ),
        migrations.RenameField(
            model_name='annotationapproval',
            old_name='ontology_term_link',
            new_name='ontology_term',
        ),
        migrations.RenameField(
            model_name='historicalannotation',
            old_name='ontology_term_link',
            new_name='ontology_term',
        ),
    ]
