# Generated by Django 3.2.7 on 2023-10-24 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0010_annotationontologyterm_term_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotationontologyterm',
            name='aspect',
            field=models.PositiveSmallIntegerField(choices=[(1, 'PO Plant Anatomy'), (2, 'PO Plant Growth'), (3, 'TO Trait'), (4, 'PECO Experimental condition'), (5, 'PSO Stress'), (6, 'GO Biological Process'), (7, 'GO Cellular Component'), (8, 'GO Molecular Function')], default=99),
        ),
    ]
