# Generated by Django 3.2.5 on 2021-08-12 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Taxon',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('rank', models.CharField(max_length=32)),
                ('related_synonyms', models.CharField(blank=True, max_length=255)),
                ('exact_synonyms', models.CharField(blank=True, max_length=255)),
                ('ncbi_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='taxon.taxon')),
            ],
        ),
    ]
