# Generated by Django 3.2.5 on 2021-08-13 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxonomyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='taxonomy/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='taxon',
            name='parent',
            field=models.PositiveIntegerField(),
        ),
    ]
