# Generated by Django 3.2.5 on 2021-08-13 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxon', '0002_auto_20210813_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxon',
            name='exact_synonyms',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='taxon',
            name='related_synonyms',
            field=models.TextField(blank=True, max_length=2000),
        ),
    ]
